spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASS}

antivirus:
  redis:
    prefix: "file:scan:"
    ttl-hours: 24

  rabbitmq:
    exchanges:
      tasks: "antivirus.tasks.direct"
      results: "antivirus.results.direct"

    queues:
      tasks: "antivirus.tasks.queue"
      results: "antivirus.results.queue"

    routing-keys:
      tasks: "scan.task.v1"
      results: "scan.result.v1"

  clamav:
    host: ${CLAMAV_HOST}
    port: ${CLAMAV_PORT}

  scan:
    fast:
      read-limit: 8192

    full-scan-threshold-mb: 100

  scheduling:
    signature-update:
      interval: "PT15M"

  s3:
    url: ${S3_URL}
    access-key: ${S3_ACCESS_KEY}
    secret-key: ${S3_SECRET_KEY}
    region: ${S3_REGION}

    user-data-bucket:
      name: ${S3_BUCKET_NAME}